### PR TITLE
resolve paths with build number `latest` to last available artifact, …

### LINKED ISSUE #2: Provide stable symlinks for something $latest build
I'd be useful to resolve something like `/artifacts/latest/5-2/artifact.txt` to `/artifcats/9001/5-2/artifacts.txt`.

### PR DESCRIPTION
**Pull request by felixb**
…fixes #2

### CODE REVIEW

**Comment by flosell** [comment]
Looks good to me. Could you add a route to `artifact-handler-for` and a small mention of the feature in the `README.md`? Then it's ready to merge

**Comment by felixb** [comment]
I added a note to the readme. I think routing is working already. Do we really need an explicit route?

**Comment by flosell** [comment]
Sorry, didn't catch the 'if latest'. All good, thanks for the contribution!

**Comment by felixb** [comment]
Do you mind releasing the new code base?

**Comment by flosell** [comment]
Done: [`[lambdacd-artifacts "0.1.1"]`](https://github.com/flosell/lambdacd-artifacts/releases)

**Pull request merged**
